name: Fluffy
version: 1.0-SNAPSHOT
main: me.antritus.astral.fluffycombat.FluffyCombat
api-version: '1.20'
authors: [antritus]

load-after:
  - name: Wormhole
    bootstrap: false

dependencies:
  - name: Wormhole
    required: true
    bootstrap: false
